# Generated by Django 3.1.8 on 2021-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=5)),
                ('faculty', models.CharField(max_length=500)),
            ],
        ),
    ]
